Form/Type/GeoChoiceType.php
<?php

namespace ADW\MindboxBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GeoChoiceType extends AbstractType
{
    public function getParent()
    {
        return TextType::class;
    }

    public function getBlockPrefix()
    {
        return 'adw_mindbox__geo_choice';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

Resources/views/Profiler/mindbox.html.twig
{% extends 'WebProfilerBundle:Profiler:layout.html.twig' %}

{% block toolbar %}
    {% set icon %}
        <span class="sf-toolbar-value">{{ collector.customer }}</span>
        <span class="sf-toolbar-label">Mindbox</span>
    {% endset %}

{#    {% set text %}
    <div class="sf-toolbar-info-piece">
        <b>Customer</b>
        <span>{{ collector.customer | default ('No') }}</span>
    </div>
    <div class="sf-toolbar-info-piece">
        <b>Allowed Operations</b>
        {% for operation in collector.allowedOperations %}
            <span>{{ operation.name }}</span>
        {% endfor %}
    </div>
    {% endset %}#}

    {{ include('@WebProfiler/Profiler/toolbar_item.html.twig', { link: profiler_url }) }}
{% endblock %}

{% block menu %}
    <span class="label">
        <strong>Mindbox</strong>
        <span class="count"><span>{{ collector.customer }}</span></span>
    </span>
{% endblock %}

{% block panel %}
    <h3>Allowed Operations</h3>
    <table>
        <thead>
        <tr>
            <td scope="col">Operation</td>
        </tr>
        </thead>
        <tbody>
        {% for operation in collector.allowedOperations %}
            <tr>
                <td>{{ operation.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h3>Denied Operations</h3>
    <table>
        <thead>
        <tr>
            <td scope="col">Operation</td>
            <td scope="col">Required Operation</td>
        </tr>
        </thead>
        <tbody>
        {% for operation in collector.deniedOperations %}
            <tr>
                <td>{{ operation.name }}</td>
                <td>{{ operation.requiredOperation }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}